### ISSUE TITLE
FY=2022 for US 2021  calendar year 

### ISSUE THREAD

**Issue by simoami** [adamjstewart/fiscalyear#23]
Hello, If my assumption is correct, I was expecting the lib to return `fiscal_year=2021` when the calendar is set to start on January to follow the calendar year, since the end date (2021-12-31) still falls in 2021. 

Code to reproduce:

```python
import fiscalyear
import datetime

start_month = 1
sdate = datetime.datetime(2021, 1, 1)

with fiscalyear.fiscal_calendar(start_day=1, start_month=start_month, start_year='previous'):
  f = fiscalyear.FiscalDate(sdate.year, sdate.month, sdate.day)
  print('ISO:', f.isoformat(), ' FY:',  f.fiscal_year, ' FQ:', f.fiscal_quarter, ' FM:', f.fiscal_month)
  fy = fiscalyear.FiscalYear(f.fiscal_year)
  print('FY period:', fy.start.date(), '/', fy.end.date())
```

Output:
```
ISO: 2021-01-01  FY: 2022  FQ: 1  FM: 1
FY period: 2021-01-01 / 2021-12-31
```
Is this expected? if yes, how does one switch to standard year when following the calendar year?

**Comment by adamjstewart** [comment]
Yes, this behavior looks correct. To get the behavior you're expecting, change `start_year` to `'same'` instead of `'previous'`.

For most users, the fiscal year does not start on January 1st. If it did, they could just use Python's builtin datetime module instead. This library is primarily designed for a fiscal year that does not coincide with a calendar year.

For example, let's say the fiscal year starts on October 1st (U.S. federal government fiscal calendar). This information alone is not sufficient, because it's ambiguous whether the 2021 fiscal year starts in 2021 and ends in 2022 or starts in 2020 and ends in 2021 (both are used depending on the fiscal calendar). The former corresponds to 'same', while the latter corresponds to 'previous'.
