### ISSUE TITLE
[Question]: Why is the implementation primarily inside of `__init__.py`?

### ISSUE THREAD

**Issue by galenseilis** [adamjstewart/fiscalyear#32]
I just noticed that the code is primarily inside a [`__init__.py`](https://github.com/adamjstewart/fiscalyear/blob/main/fiscalyear/__init__.py). That's an unconventional choice which seems to work fine, but I'm just curious why it was made as a design choice for this package.

**Comment by adamjstewart** [comment]
This is for historical reasons. The original implementation was a single `fiscalyear.py` file, similar to how `six` is packaged. However, in order to add type hints to the library, you have to add a `py.typed` file in the package directory. So I created a `fiscalyear` directory, added `py.typed`, and renamed `fiscalyear.py` to `fiscalyear/__init__.py` to keep the imports the same.

**Comment by galenseilis** [comment]
Alright, thank you for that summary.
